name = str(input("ENTER YOUR NAME:"))
age = float(input("ENTER YOUR AGE:"))
print(name,age)
if(age<=4):
    print("Your ticket price is 10 rupees")
if(age >=5):
    print("Your ticket price is 45 rupees") 
count=name.count('h')
print(count)
capital=name.title()
print(capital)
upper=name.upper()
print(upper)
count1=name.count('')
print(count1)
